Gorevcim.WEB/Controllers/ProductsVatController.cs
using Microsoft.AspNetCore.Mvc;
using Gorevcim.Core.Services;
using Gorevcim.Core.DTOs;
using Gorevcim.Core;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using Gorevcim.Core.Models;

namespace Gorevcim.WEB.Controllers
{
    public class ProductsVatController : Controller
    {
        private readonly IProductVatUnitsService _productVatUnitsService;
        private readonly IMapper _mapper;

        public ProductsVatController(IProductVatUnitsService productVatUnitsService, IMapper mapper)
        {
            _productVatUnitsService = productVatUnitsService;
            _mapper = mapper;
        } 

        public async Task<IActionResult> Index()
        {
            var productVat = await _productVatUnitsService.GetWebAllProductVatUnits();
            dynamic mymodel = new ExpandoObject();
            mymodel._productVat = productVat;
            mymodel.activeProductVatCount = productVat.Where(t => t.IsActive == 1).Count();
            mymodel.passiveProductVatCount = productVat.Where(t => t.IsActive == 0).Count();
            return View(mymodel);
        }



        public async Task<IActionResult> Save()
        {
            var productVat = await _productVatUnitsService.GetAllAsync(); //    var productsColor = await _productColorsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(productVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name");
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Save(ProductVatUnitsDto productVatUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productVatUnitsService.AddAsync(_mapper.Map<ProductVatUnits>(productVatUnitsDto));
                TempData.Add("Success", "Ürün başarıyla eklenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Error", "Hata Oluştu. ProductsController|Save|54");
            var productVat = await _productVatUnitsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(productVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int Id)
        {
            var productVat = await _productVatUnitsService.GetByIdAsync(Id);
            var ProductVat = await _productVatUnitsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(ProductVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name", productVat);
            return View(_mapper.Map<ProductVatUnitsDto>(productVat));
        }



        [HttpPost]
        public async Task<IActionResult> Update(ProductVatUnitsDto productVatUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productVatUnitsService.UpdateAsync(_mapper.Map<ProductVatUnits>(productVatUnitsDto));
                TempData.Add("Info", "Ürün başarıyla güncellenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Info", "Hata Oluştu. ProductsController|Update|79");
            var productVat = await _productVatUnitsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(productVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name", productVatDto);
            return View();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var productVat = await _productVatUnitsService.GetByIdAsync(Id);
            await _productVatUnitsService.RemoveAsync(productVat);
            TempData.Add("Info", "Ürün başarıyla silinmiştir.");
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int Id)
        {
            var productVat = await _productVatUnitsService.GetByIdAsync(Id);
            var ProductVat = await _productVatUnitsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(ProductVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name", productVat);
            return View(_mapper.Map<ProductVatUnitsDto>(productVat));
        }





    }
}

Gorevcim.WEB/Views/ProductsVat/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model ProductVatUnitsDto 

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsVat" asp-action="Details" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Ölçü Detay</h4>
                <input type="hidden" asp-for="ProductVatId" id="ProductColorIdDetails">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label">Adı</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsNameDetails" asp-for="Name" type="text" class="form-control" disabled>

                    </div>
                </div>



                <div class="mb-3 row">
                    <label asp-for="Code" class="col-md-2 col-form-label">Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsWebUrlDetails" asp-for="Code" type="text" class="form-control" disabled>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label">Açıklama</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsWebUrlDetails" asp-for="Explanation" type="text" class="form-control" disabled>

                    </div>
                </div>
 
            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsVat/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model dynamic


<div class="row">
    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Aktif Kdv Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.activeProductVatCount</span></h5>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Pasif Kdv Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.passiveProductVatCount</span></h5>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kdv Table</h4>
            <div class="table-rep-plugin">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="ProductsProjectTable" role="grid">

                        <thead>
                            <tr>
                                
                                <th>Name</th>
                                <th>Code</th>
                                <th>Açıklama</th>
                                <th>Aksiyonlar</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model._productVat)
                            {
                                <tr>
                                    
                                    <td>@item.Name</td>
                                    <td>@item.Code</td>
                                    <td>@item.Explanation</td>
                             
                                    <td>
                                        <ul class="list-inline mb-0">

                                            <li class="list-inline-item">
                                                <a class="px-2 text-info" asp-controller="ProductsVat" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="uil uil-arrow-from-right font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-primary" asp-controller="ProductsVat" asp-action="Update" asp-route-id="@item.Id">
                                                    <i class="uil uil-pen font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-danger" data-bs-toggle="modal" data-bs-target="#modalDelete@(item.Id)">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                            </li>

                                        </ul>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel">Kdv @(item.Name) siliniyor.</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>

                                                      Kdv Adı: @(item.Name)<br>
                                                      Kdv Kodu : @(item.Code)

                                                    <strong>Kdv: @(item.Name)</strong> kalıcı olarak <strong>silinecektir.</strong>

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light waves-effect" data-bs-dismiss="modal">iptal</button>
                                                <a type="button" class="btn btn-primary waves-effect waves-light" asp-controller="ProductsVat" method="post" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                                <!-- /.modal -->
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>




</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ProductsCategoryTable').DataTable(

                {
                    language: {
                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",

                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },
                    },
                    dom: 'Bfrltip',
                    buttons: [
                        'copy', 'excel', 'pdf', 'print'
                    ],
                    responsive: true

                }

            );
        });
    </script>

}

Gorevcim.WEB/Views/ProductsVat/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model ProductVatUnitsDto




<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-action="Save" method="post" asp-controller="ProductsVat" class="needs-validation" novalidate>
                <h4 class="card-title">Kdv Kayıt</h4>



                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectBrandsNameSave">Adı</label>
                    <div class="col-md-6">
                        <input asp-for="Name" type="text" class="form-control" id="ProductProjectNameSave" placeholder="Kdv Birimi Yazınız" required>
                        <div class="invalid-feedback"> Kdv Birimi Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Code" class="col-md-2 col-form-label"> Kod</label>
                    <div class="col-md-6">
                        <input asp-for="Code" id="BrandsWebUrlSave" class="form-control" type="text" placeholder="Kdv Birimi Kodu Yazınız" required>
                        <div class="invalid-feedback">Kdv Birimi Kodu Boş olamaz!</div>
                    </div>
                </div>



                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label"> Açıklama </label>
                    <div class="col-md-6">
                        <input asp-for="Explanation" id="BrandsWebUrlSave" class="form-control" type="text" placeholder="Açıklama Yazınız" required>
                        <div class="invalid-feedback">Açıklama Birimi Kodu Boş olamaz!</div>
                    </div>
                </div>

   

                <input type="submit" class="btn btn-primary waves-effect waves-light me-1 form-group" />




            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsVat/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model ProductVatUnitsDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsVat" asp-action="Update" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Kdv Birimi  Güncelle</h4>
                <input type="hidden" asp-for="ProductVatId" id="ProductProjectIdUpdate">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectNameSave">Kdv Adı</label>
                    <div class="col-md-6">
                        <input id="ProductProjectNameUpdate" asp-for="Name" type="text" class="form-control" placeholder="Kdv Adı Yazınız" required>
                        <div class="invalid-feedback">Kdv Adı Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Code" class="col-md-2 col-form-label">Kdv Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductProjectCodeUpdate" asp-for="Code" type="text" class="form-control" placeholder="Kdv Kodunu Yazınız" required>
                        <div class="invalid-feedback">Kdv Kodu Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label">Açıklama</label>
                    <div class="col-md-6">
                        <input id="ProductProjectCodeUpdate" asp-for="Explanation" type="text" class="form-control" placeholder="Açıklama Yazınız" required>
                        <div class="invalid-feedback">Açıklama Boş olamaz!</div>
                    </div>
                </div>


                <input type="submit" value="Güncelle" class="btn btn-primary waves-effect waves-light me-1 form-group" />











            </form>


        </div>
    </div>
</div>