Gorevcim.WEB/Controllers/ProductsCurrencyController.cs
using Microsoft.AspNetCore.Mvc;
using Gorevcim.Core.Services;
using Gorevcim.Core.DTOs;
using Gorevcim.Core;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using Gorevcim.Core.Models;

namespace Gorevcim.WEB.Controllers
{
    public class ProductsCurrencyController : Controller
    {
        private readonly IProductCurrencyUnitsService _productCurrencyUnitsService;
        private readonly IMapper _mapper;

        public ProductsCurrencyController(IProductCurrencyUnitsService productCurrencyUnitsService, IMapper mapper)
        {
            _productCurrencyUnitsService = productCurrencyUnitsService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var productCurrency = await _productCurrencyUnitsService.GetWebAllProductCurrency();
            dynamic mymodel = new ExpandoObject();
            mymodel._productCurrency = productCurrency;
            mymodel.activeProductCurrencyCount = productCurrency.Where(t => t.IsActive == 1).Count();
            mymodel.passiveProductCurrencyCount = productCurrency.Where(t => t.IsActive == 0).Count();
            return View(mymodel);
        }



        public async Task<IActionResult> Save()
        {
            var productCurrency = await _productCurrencyUnitsService.GetAllAsync(); //    var productsColor = await _productColorsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(productCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name");
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Save(ProductCurrencyUnitsDto productCurrencyUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productCurrencyUnitsService.AddAsync(_mapper.Map<ProductCurrencyUnits>(productCurrencyUnitsDto));
                TempData.Add("Success", "Ürün başarıyla eklenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Error", "Hata Oluştu. ProductsController|Save|54");
            var productCurrency = await _productCurrencyUnitsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(productCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int Id)
        {
            var productCurrency = await _productCurrencyUnitsService.GetByIdAsync(Id);
            var ProductCurrency = await _productCurrencyUnitsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(ProductCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name", productCurrency);
            return View(_mapper.Map<ProductCurrencyUnitsDto>(productCurrency));
        }



        [HttpPost]
        public async Task<IActionResult> Update(ProductCurrencyUnitsDto productCurrencyUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productCurrencyUnitsService.UpdateAsync(_mapper.Map<ProductCurrencyUnits>(productCurrencyUnitsDto));
                TempData.Add("Info", "Ürün başarıyla güncellenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Info", "Hata Oluştu. ProductsController|Update|79");
            var productCurrency = await _productCurrencyUnitsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(productCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name", productCurrencyDto);
            return View();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var productCurrency = await _productCurrencyUnitsService.GetByIdAsync(Id);
            await _productCurrencyUnitsService.RemoveAsync(productCurrency);
            TempData.Add("Info", "Ürün başarıyla silinmiştir.");
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int Id)
        {
            var productCurrency = await _productCurrencyUnitsService.GetByIdAsync(Id);
            var ProductCurrency = await _productCurrencyUnitsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(ProductCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name", productCurrency);
            return View(_mapper.Map<ProductCurrencyUnitsDto>(productCurrency));
        }





    }
}

Gorevcim.WEB/Views/ProductsCurrency/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model ProductCurrencyUnitsDto 

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsCurrency" asp-action="Details" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Para Detay</h4>
                <input type="hidden" asp-for="ProductCurrencyId" id="ProductColorIdDetails">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label">Adı</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsNameDetails" asp-for="Name" type="text" class="form-control" disabled>

                    </div>
                </div>



                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label">Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsWebUrlDetails" asp-for="ShortCode" type="text" class="form-control" disabled>

                    </div>
                </div>

 
            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsCurrency/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model dynamic


<div class="row">
    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Aktif Para Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.activeProductCurrencyCount</span></h5>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Pasif Para Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.passiveProductCurrencyCount</span></h5>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Marka Table</h4>
            <div class="table-rep-plugin">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="ProductsProjectTable" role="grid">

                        <thead>
                            <tr>
                                
                                <th>Name</th>
                                <th>ShortCode</th>
                                <th>Aksiyonlar</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model._productCurrency)
                            {
                                <tr>
                                    
                                    <td>@item.Name</td>
                                    <td>@item.ShortCode</td>
                             
                                    <td>
                                        <ul class="list-inline mb-0">

                                            <li class="list-inline-item">
                                                <a class="px-2 text-info" asp-controller="ProductsCurrency" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="uil uil-arrow-from-right font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-primary" asp-controller="ProductsCurrency" asp-action="Update" asp-route-id="@item.Id">
                                                    <i class="uil uil-pen font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-danger" data-bs-toggle="modal" data-bs-target="#modalDelete@(item.Id)">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                            </li>

                                        </ul>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel">Proje @(item.Name) siliniyor.</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>

                                                      Para Adı: @(item.Name)<br>
                                                      Para Kodu : @(item.ShortCode)

                                                    <strong>Para: @(item.Name)</strong> kalıcı olarak <strong>silinecektir.</strong>

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light waves-effect" data-bs-dismiss="modal">iptal</button>
                                                <a type="button" class="btn btn-primary waves-effect waves-light" asp-controller="ProductsCurrency" method="post" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                                <!-- /.modal -->
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>




</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ProductsCategoryTable').DataTable(

                {
                    language: {
                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",

                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },
                    },
                    dom: 'Bfrltip',
                    buttons: [
                        'copy', 'excel', 'pdf', 'print'
                    ],
                    responsive: true

                }

            );
        });
    </script>

}

Gorevcim.WEB/Views/ProductsCurrency/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model ProductCurrencyUnitsDto




<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-action="Save" method="post" asp-controller="ProductsCurrency" class="needs-validation" novalidate>
                <h4 class="card-title">Para Kayıt</h4>



                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectBrandsNameSave">Adı</label>
                    <div class="col-md-6">
                        <input asp-for="Name" type="text" class="form-control" id="ProductProjectNameSave" placeholder="Para Birimi Yazınız" required>
                        <div class="invalid-feedback"> Para Adı Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label">Kısa Kod</label>
                    <div class="col-md-6">
                        <input asp-for="ShortCode" id="BrandsWebUrlSave" class="form-control" type="text" placeholder="Para Birimi Kodu Yazınız" required>
                        <div class="invalid-feedback">Para Birimi Kodu Boş olamaz!</div>
                    </div>
                </div>

   

                <input type="submit" class="btn btn-primary waves-effect waves-light me-1 form-group" />




            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsCurrency/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model ProductCurrencyUnitsDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsCurrency" asp-action="Update" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Para Güncelle</h4>
                <input type="hidden" asp-for="ProductCurrencyId" id="ProductProjectIdUpdate">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectNameSave">Para Adı</label>
                    <div class="col-md-6">
                        <input id="ProductProjectNameUpdate" asp-for="Name" type="text" class="form-control" placeholder="Para Id Yazınız" required>
                        <div class="invalid-feedback">Para Id Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label">Para Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductProjectCodeUpdate" asp-for="ShortCode" type="text" class="form-control" placeholder="Para Kodunu Yazınız" required>
                        <div class="invalid-feedback">Para Kodunu  olamaz!</div>
                    </div>
                </div>



                <input type="submit" value="Güncelle" class="btn btn-primary waves-effect waves-light me-1 form-group" />











            </form>


        </div>
    </div>
</div>