Gorevcim.WEB/Controllers/CompanyController.cs
using AutoMapper;
using Gorevcim.Core.DTOs;
using Gorevcim.Core.Models;
using Gorevcim.Core.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using Gorevcim.Service.Services;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Gorevcim.WEB.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;

        public CompanyController(ICompanyService companyService, IMapper mapper)
        {
            _companyService = companyService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var company = await _companyService.GetWebAllCompanyAsync();
            dynamic mymodel = new ExpandoObject();
            mymodel._company = company;
            mymodel.activeCompanyCount = company.Where(t => t.IsActive == 1).Count();
            mymodel.passiveCompanyCount = company.Where(t => t.IsActive == 0).Count();
            return View(mymodel);
        }



        public async Task<IActionResult> Save()
        {
            var company = await _companyService.GetAllAsync();
            var companyDto = _mapper.Map<List<CompanyDto>>(company.ToList());
            ViewBag.company = new SelectList(companyDto, "Id", "Name");
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Save(CompanyDto companyDto)
        {
            if (ModelState.IsValid)
            {
                await _companyService.AddAsync(_mapper.Map<Company>(companyDto));
                TempData.Add("Success", "Firma başarıyla eklenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Error", "Hata Oluştu. CompanyController|Save|54");
            var company = await _companyService.GetAllAsync();
            var CompanyDto = _mapper.Map<List<CompanyDto>>(company.ToList());
            ViewBag.company = new SelectList(CompanyDto, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int Id)
        {
            var company = await _companyService.GetByIdAsync(Id);
            var Company = await _companyService.GetAllAsync();
            var companyDto = _mapper.Map<List<CompanyDto>>(Company.ToList());
            ViewBag.company = new SelectList(companyDto, "Id", "Name", company);
            return View(_mapper.Map<CompanyDto>(company));
        }



        [HttpPost]
        public async Task<IActionResult> Update(CompanyDto companyDto)
        {
            if (ModelState.IsValid)
            {
                await _companyService.UpdateAsync(_mapper.Map<Company>(companyDto));
                TempData.Add("Info", "Firma başarıyla güncellenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Info", "Hata Oluştu. CompanyController|Update|79");
            var company = await _companyService.GetAllAsync();
            var CompanyDto = _mapper.Map<List<CompanyDto>>(company.ToList());
            ViewBag.company = new SelectList(CompanyDto, "Id", "Name", CompanyDto);
            return View();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var company = await _companyService.GetByIdAsync(Id);
            await _companyService.RemoveAsync(company);
            TempData.Add("Info", "Firma başarıyla silinmiştir.");
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int Id)
        {
            var company = await _companyService.GetByIdAsync(Id);
            var Companies= await _companyService.GetAllAsync();
            var companyDto = _mapper.Map<List<CompanyDto>>(Companies.ToList());
            ViewBag.company = new SelectList(companyDto, "Id", "Name", company);
            return View(_mapper.Map<CompanyDto>(company));
        }





    }
}

Gorevcim.WEB/Views/Company/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model CompanyDto 

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="Company" asp-action="Details" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Firma</h4>
                <input type="hidden" asp-for="Id" id="CompanyIdUpdate">

                <div class="mb-3 row">
                    <label asp-for="Id" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <select id="CompanyIdUpdate" asp-for="Name" asp-items="ViewBag.company" class="form-select" disabled readonly></select>
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="CompanyNameSave">Firma Adı</label>
                    <div class="col-md-6">
                        <input id="CompanyNameUpdate" asp-for="Name" type="text" class="form-control" placeholder="Firma Adını Yazınız" disabled readonly >
                        
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="CompanyDescription" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyDescriptionUpdate" asp-for="CompanyDescription" type="text" class="form-control" disabled readonly>
                        
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="Adress" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="Adress" asp-for="CompanyDescription" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Country" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyCountryId" asp-for="Country" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="City" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyCityId" asp-for="City" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="EMail" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyEMailId" asp-for="EMail" type="text" class="form-control" disabled readonly>

                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="PhoneNumber" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyPhoneNumberId" asp-for="PhoneNumber" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="CompanyWebUrl" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyCompanyWebUrlId" asp-for="CompanyWebUrl" type="text" class="form-control" disabled readonly>

                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="TaxNumber" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyTaxNumberId" asp-for="TaxNumber" type="text" class="form-control" disabled readonly>

                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="TaxAdministration" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyTaxAdministrationId" asp-for="TaxAdministration" type="text" class="form-control" disabled readonly>

                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="InvoiceAddress" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyInvoiceAddressId" asp-for="InvoiceAddress" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="InvoiceMailAddress" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyInvoiceMailAddressId" asp-for="InvoiceMailAddress" type="text" class="form-control" disabled readonly>

                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="CompanyType" class="col-md-2 col-form-label"></label>
                    <div class="col-md-6">
                        <input id="CompanyTypeId" asp-for="CompanyType" type="text" class="form-control" disabled readonly>

                    </div>
                </div>


            </form>


   

        </div>
    </div>
</div>

Gorevcim.WEB/Views/Company/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model dynamic


<div class="row">
<div class="col-md-6 col-xl-2">
    <div class="card">
        <div class="card-body">
            <div>
                <p class="text-muted mb-0">Aktif Firma Sayısı</p>
                <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.activeCompanyCount</span></h5>                
            </div> 
        </div>
    </div>
</div>

<div class="col-md-6 col-xl-2">
    <div class="card">
        <div class="card-body">
            <div>
                <p class="text-muted mb-0">Pasif Firma Sayısı</p>
                <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.passiveCompanyCount</span></h5>                
            </div> 
        </div>
    </div>
</div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Firma Tablosu</h4>
            <div class="table-rep-plugin">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="ProductsColorTable" role="grid">

                        <thead>
                            <tr>
                                <th>Id</th>                            
                                <th>Firma Adı</th>
                                <th>Şirket Tanımı</th>
                                <th>Adres</th>
                                <th>Ülke</th>
                                <th>Şehir</th>
                                <th>E-Mail</th>
                                <th>Telefon</th>
                                <th>Web Adresi</th>
                                <th>Vergi Numarası</th>
                                <th>Vergi Dairesi</th>
                                <th>Fatura Adresi</th>
                                <th>Fatura Mail Adresi</th>
                                <th>Firma Türü</th>
                                <th>Açıklama</th>
                                <th>Aksiyonlar</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model._company)
                            {
                                <tr>
                                    <td>@item.Id</td>                               
                                    <td>@item.Name</td>
                                    <td>@item.CompanyDescription</td>
                                    <td>@item.Adress</td>
                                    <td>@item.Country</td>
                                    <td>@item.City</td>
                                    <td>@item.EMail</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CompanyWebUrl</td>
                                    <td>@item.TaxNumber</td>
                                    <td>@item.TaxAdministration</td>
                                    <td>@item.InvoiceAddress</td>
                                    <td>@item.InvoiceMailAddress</td>
                                    <td>@item.CompanyType</td>
                                    <td>@item.Explanation</td>
                                    <td>
                                        <ul class="list-inline mb-0">

                                            <li class="list-inline-item">
                                                <a class="px-2 text-info" asp-controller="Company" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="uil uil-arrow-from-right font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-primary" asp-controller="Company" asp-action="Update" asp-route-id="@item.Id">
                                                    <i class="uil uil-pen font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-danger" data-bs-toggle="modal" data-bs-target="#modalDelete@(item.Id)">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                            </li>
                                 
                                        </ul>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel">Firma @(item.Name) siliniyor.</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                   <strong>Firma:  @(item.Name)</strong>  kalıcı olarak  <strong>silinecektir.</strong>
                                                   <strong>Firma Id: </strong> @(item.Id)<br>
                                                    
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light waves-effect" data-bs-dismiss="modal">iptal</button>
                                                <a type="button" class="btn btn-primary waves-effect waves-light" asp-controller="Company" method="post" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                                <!-- /.modal -->
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>




</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#ProductsColorTable').DataTable(

                {
                    language: {
                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",

                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },
                    },
                    dom: 'Bfrltip',
                    buttons: [
                        'copy', 'excel', 'pdf', 'print'
                    ],
                    responsive: true

                }

            );
        });
    </script>
    }

Gorevcim.WEB/Views/Company/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model CompanyDto




<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form  asp-action="Save" method="post" asp-controller="Company" class="needs-validation" novalidate>
                <h4 class="card-title">Firma Kayıt</h4>


        

                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="CompanyNameSave">Firma Adı</label>
                    <div class="col-md-6">
                        <input asp-for="Name" type="text" class="form-control" id="CompanyNameSave" placeholder="Firma Adını Yazınız" required>
                        <div class="invalid-feedback">Firma Adı Boş olamaz!</div>
                    </div>
                </div>

               <div class="mb-3 row">
                    <label asp-for="CompanyDescription" class="col-md-2 col-form-label">Firma Tanımı</label>
                    <div class="col-md-6">
                        <input asp-for="CompanyDescription" id="CompanyDescriptionSave" class="form-control" type="text" placeholder="Şirket Tanımını Yazınız" required>
                        <div class="invalid-feedback">Firma Tanımı Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Adress" class="col-md-2 col-form-label" for="CompanyAdressSave">Firma Adresi</label>
                    <div class="col-md-6">
                        <input asp-for="Adress" type="text" class="form-control" id="AdressSave" placeholder="Firma Adresini Yazınız" required>
                        <div class="invalid-feedback">Firma Adresi Boş olamaz!</div>
                    </div>
                </div>


                  <div class="mb-3 row">
                    <label asp-for="Country" class="col-md-2 col-form-label" for="CompanyCountrySave">Ülke</label>
                    <div class="col-md-6">
                        <input asp-for="Country" type="text" class="form-control" id="CountrySave" placeholder="Ülke Yazınız" required>
                        <div class="invalid-feedback">Ülke Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="City" class="col-md-2 col-form-label" for="CompanyCitySave">Şehir</label>
                    <div class="col-md-6">
                        <input asp-for="City" type="text" class="form-control" id="CitySave" placeholder="Şehir Yazınız" required>
                        <div class="invalid-feedback">Şehir Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="EMail" class="col-md-2 col-form-label" for="CompanyEMailSave">E-Mail</label>
                    <div class="col-md-6">
                        <input asp-for="EMail" type="text" class="form-control" id="EMailSave" placeholder="E-Mail Yazınız" required>
                        <div class="invalid-feedback">E-Mail Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="PhoneNumber" class="col-md-2 col-form-label" for="CompanyPhoneNumberSave">Telefon</label>
                    <div class="col-md-6">
                        <input asp-for="PhoneNumber" type="text" class="form-control" id="PhoneSave" placeholder="Telefon Yazınız" required>
                        <div class="invalid-feedback">Telefon Boş olamaz!</div>
                    </div>
                </div>

                      <div class="mb-3 row">
                    <label asp-for="CompanyWebUrl" class="col-md-2 col-form-label" for="CompanyWebUrlSave">WEB Adresi</label>
                    <div class="col-md-6">
                        <input asp-for="CompanyWebUrl" type="text" class="form-control" id="CompanyWebUrlSave" placeholder="WEB Adresi Yazınız" required>
                        <div class="invalid-feedback">WEB Adresi Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="TaxNumber" class="col-md-2 col-form-label" for="TaxNumberlSave">Vergi Numarası</label>
                    <div class="col-md-6">
                        <input asp-for="TaxNumber" type="text" class="form-control" id="TaxNumberSave" placeholder="Vergi Numarasını Yazınız" required>
                        <div class="invalid-feedback">Vergi Numarası Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="TaxAdministration" class="col-md-2 col-form-label" for="TaxAdministrationSave">Vergi Dairesi</label>
                    <div class="col-md-6">
                        <input asp-for="TaxAdministration" type="text" class="form-control" id="TaxAdministrationSave" placeholder="Vergi Dairesini Yazınız" required>
                        <div class="invalid-feedback">Vergi Dairesi Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="InvoiceAddress" class="col-md-2 col-form-label" for="InvoiceAddressSave">Fatura Adresi</label>
                    <div class="col-md-6">
                        <input asp-for="InvoiceAddress" type="text" class="form-control" id="InvoiceAddressSave" placeholder="Fatura Adresini Yazınız" required>
                        <div class="invalid-feedback">Fatura Adresi Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="InvoiceMailAddress" class="col-md-2 col-form-label" for="InvoiceMailAddressSave">Fatura Mail Adresi</label>
                    <div class="col-md-6">
                        <input asp-for="InvoiceMailAddress" type="text" class="form-control" id="InvoiceMailAddressSave" placeholder="Fatura Mail Adresini Yazınız" required>
                        <div class="invalid-feedback">Fatura Mail Adresi Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="CompanyType" class="col-md-2 col-form-label" for="CompanyTypeSave">Firma Türü </label>
                    <div class="col-md-6">
                        <input asp-for="CompanyType" type="text" class="form-control" id="CompanyTypeSave" placeholder="Firma Türünü Yazınız" required>
                        <div class="invalid-feedback">Firma Türü Boş olamaz!</div>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label" for="CompanyTypeSave">Açıklama </label>
                    <div class="col-md-6">
                        <input asp-for="Explanation" type="text" class="form-control" id="CompanyExpSave" placeholder="Firma Açıklamasını Yazınız" required>
                        <div class="invalid-feedback">Firma Açıklaması  Boş olamaz!</div>
                    </div>
                </div>


                
                <input type="submit" class="btn btn-primary waves-effect waves-light me-1 form-group" />

            </form>


        </div>
    </div>
</div>